import enum
from sqlalchemy.types import *

# For ENUM Definitions, you should define it in this manner
# variable_name = Enum(enum.Enum('variable_name', {'EnumChoice0': 0, 'EnumChoice1': 1, ....}))
# Otherwise, if you are not using keywords or strings with spaces at enum choices, you can define it as follows

class StudentCoursesStatusStatusEnum(enum.Enum):
    Eligible = 1
    Progress = 2
    Completed = 3

class UserMarketTimingOrientationStatusEnum(enum.Enum):
    Active = 1
    Progress = 2

# DEV NOTE: Some of the table override definitions have been commented out due to errors encountered
# Should perform testing to check if defaults work (Although that should not be the case.....)

# DATA_TYPE DEFINITION (Needed to explicately ensure correct data type)
# NOTE: Only some columns have been defined, the rest can be handled using defaults
# Recommendation: While not necessary, you should still define all the columns in the table to prevent unexpected behaviour
custom_data_types = {
    'actual_trade': {
            'date': Date,
            'time': Time,
            'level': VARCHAR(length=250),
            'amount': VARCHAR(length=250),
            'flag_type': SMALLINT,
            'market_timing_rule': VARCHAR(length=255),
            'rules_followed': VARCHAR(length=255),
            'profitable_trade': SMALLINT, 
            'trade_plan_followed': SMALLINT,
            'status': SMALLINT,
        },
    'actual_trade_setup': {
        'entry_date': Date,
        'entry_price': VARCHAR(length=250),
        'entry_quantity': BigInteger,
        'exit_date': Date,
        'exit_price': VARCHAR(length=250),
        'exit_quantity': BigInteger,
    },
    'agent_availability': {
        'title': VARCHAR(length=255),
        'start_date': Date,
        'end_date': Date,
        'start_time': Interval,
        'end_time': Interval,
        'sunday': SMALLINT,
        'monday': SMALLINT,
        'tuesday': SMALLINT,
        'wednesday': SMALLINT,
        'friday': SMALLINT,
        'saturday': SMALLINT,
        'created_at': TIMESTAMP(timezone=True),
        'deleted_at': TIMESTAMP(timezone=True),
    },
    'agent_bookings': {
        'booking_id': VARCHAR(length=255),
        'date': Date,
        'slot_start': Interval,
        'slot_end': Interval,
        'country_code': VARCHAR(length=255),
        'phone_number': VARCHAR(length=255),
        'skype': VARCHAR(length=255),
        'created_at': TIMESTAMP(timezone=True),
    },
    'announcement': {
        'title': VARCHAR(length=250),
        'description': TEXT,
        'status': SMALLINT,
        'message': VARCHAR(length=255),
    },
    'app_notifications': {
        'notification_id': VARCHAR(length=191),
        'entity': VARCHAR(length=191),
        'entity_id': VARCHAR(length=191),
        'notification_title': VARCHAR(length=191),
        'notification_text': VARCHAR(length=191),
        'read': SMALLINT,
    },
    'articles': {
        'asset_id': VARCHAR(length=250),
        'title': VARCHAR(length=250),
        'slug': VARCHAR(length=250),
        'image': VARCHAR(length=250),
        'home_thumbnail': VARCHAR(length=500),
        'social_media': VARCHAR(length=255),
        'short_description': VARCHAR(length=250),
    },
    'asset_class': {
        'name': VARCHAR(length=500),
        'image': VARCHAR(length=500),
        'icon': VARCHAR(length=500),
        'icon_alt_tag': VARCHAR(length=500),
        'image_alt_tag': VARCHAR(length=500),
        'status': SMALLINT,
        'slug': VARCHAR(length=200),
    },
    'asset_class_subject': {
        'name': VARCHAR(length=500),
        'video': VARCHAR(length=500),
        'video_image': VARCHAR(length=500),
        'video_thumbnail_banner': VARCHAR(length=100),
        'status': SMALLINT,
        'slug': VARCHAR(length=200),
    },
    'auth_assignment': {
        'item_name': VARCHAR(length=64),
        'user_id': VARCHAR(length=64),
    },
    'auth_group': {
        'id': BIGINT,
        'name': VARCHAR(length=150),
    },
    'auth_group_permissions': {
        'id': BIGINT,
        'group_id': BIGINT,
        'permission_id': BIGINT,
    },
    'auth_item': {
        'name': VARCHAR(length=64),
        'rule_name': VARCHAR(length=64),
        'data': Text,
    },
    'auth_item_child': {
        'parent': VARCHAR(length=64),
        'child': VARCHAR(length=64),
    },
    'auth_permission': {
        'name': VARCHAR(length=255),
        'codename': VARCHAR(length=100),
    },
    'auth_user': {
        'id': BigInteger,
        'password': VARCHAR(length=128),
        'last_login': TIMESTAMP(timezone=True),
        'is_superuser': SMALLINT,
        'username': VARCHAR(length=150),
        'first_name': VARCHAR(length=150),
        'last_name': VARCHAR(length=150),
        'email': VARCHAR(length=254),
        'is_staff': SMALLINT,
        'is_active': SMALLINT,
        'date_joined': SMALLINT,
    },
    'auth_rule': {
        'name': VARCHAR(length=64),
        'created_at': BigInteger,
        'updated_at': BigInteger,
    },
    'auth_user_groups': {
        'id': BigInteger,
        'user_id': BigInteger,
        'group_id': BigInteger,
    },
    'auth_user_user_permissions': {
        'id': BigInteger,
        'user_id': BigInteger,
        'permission_id': BigInteger,
    },
    'backend_email_and_push_notifications': {
        'email': SMALLINT,
        'push_notification': SMALLINT,
        'entity': VARCHAR(length=191),
        'event': VARCHAR(length=191),
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
        'execution': Integer,
        'user_id': BigInteger,
    },
    'banner': {
        'title': VARCHAR(length=500),
        'video': VARCHAR(length=500),
        'image': VARCHAR(length=150),
        'image_alt_tag': VARCHAR(length=500),
        'play_btn_alt_tag': VARCHAR(length=500),
        'status': SMALLINT,
    },
    'badges': {
        'entity_type': VARCHAR(length=200),
        'name': VARCHAR(length=500),
        'image': VARCHAR(length=100),
    },
    'blocked_users': {
        'id': BIGINT,
        'blocked_user_id': BIGINT,
        'blocked_by': BIGINT,
        'reason': BIGINT,
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
    },
    'capture_page': {
        'name': VARCHAR(length=191),
        'url': VARCHAR(length=191),
        'fav_icon': VARCHAR(length=191),
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
        'capture_page_token': VARCHAR(length=191),
    },
    'capture_page_menu': {
        'name': VARCHAR(length=191),
        'url': VARCHAR(length=191),
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
    },
    'class_room_webinar': {
        'title': VARCHAR(length=500),
        'course_id': BIGINT,
        'subject_id': BIGINT,
        'lesson_id': BIGINT,
        'short_description': VARCHAR(length=1000),
        'start_date': DATE,
        'start_time': Interval,
        'end_time': Interval,
        'start_date_utc': DATE,
        'start_time_utc': Interval,
        'teacher_id': Text,
        'end_time_utc': Interval,
        'video_thumbnails': VARCHAR(length=500),
        'video_banner_image': VARCHAR(length=100),
        'webinar_class_room_id': VARCHAR(length=250),
        'status': SMALLINT,
        'download_status': SMALLINT,
        'webinar_language': SMALLINT,
        'video_file': VARCHAR(length=255),
        'webinar_host': VARCHAR(length=255),
        'webinar_duration': VARCHAR(length=255),
        'grid_posted_at': TIMESTAMP(timezone=True), #Does not exist yet....
    },
    'class_room_webinar_launch_url': {
        'webinar_class_room_id': VARCHAR(length=250),
        'video': VARCHAR(length=500),
        'is_teacher': SMALLINT,
        'status': SMALLINT
    },
    'classroom_comments': {
        'status': SMALLINT,
        'image_id': BIGINT,
    },
    'connection_messages': {
        'date': TIMESTAMP(timezone=True),
        'status': SMALLINT,
    },
    'comments_image': {
        'filename': VARCHAR(length=255),
        'size_kb': Float(9,2),
    },
    'contact_us': {
        'name': VARCHAR(length=250),
        'email': VARCHAR(length=250),
        'subject': VARCHAR(length=100),
        'phone_number': VARCHAR(length=250),
        'message': VARCHAR(length=1000),
    },
    'course_progress': {
        'completed': SMALLINT,
    },
    'courses': {
        'has_badge': SMALLINT,
        'priority': SMALLINT,
        'status': SMALLINT,
        'course_type': SMALLINT,
    },
    'django_admin_log': {
        'id': BigInteger,
        'action_time': TIMESTAMP(timezone=True),
        'object_id': Text,
        'object_repr': VARCHAR(length=200),
        'action_flag': SMALLINT,
        'change_message': Text,
        'content_type_id': BigInteger,
        'user_id': BigInteger,
    },
    'django_content_type': {
        'app_label': VARCHAR(length=100),
        'model': VARCHAR(length=100),
    },
    'django_migrations': {
        'app': VARCHAR(length=255),
        'name': VARCHAR(length=255),
        'applied': TIMESTAMP(timezone=True),
    },
    'django_q_ormq': {
        'id': BIGINT,
        'key': VARCHAR(length=100),
        'lock': TIMESTAMP(timezone=True), 
    },       
    'django_q_schedule': {
        'id': BIGINT,
        'func': VARCHAR(length=256),
        'hook': VARCHAR(length=256),
        'schedule_type': VARCHAR(length=1),
        'repeats': Integer,
        'next_run': TIMESTAMP(timezone=True),
        'task': VARCHAR(length=100),
        'name': VARCHAR(length=100),
        'minutes': SMALLINT,
        'cron': VARCHAR(length=100),
        'cluster': VARCHAR(length=100),
    },
    'django_q_task': {
        'name': VARCHAR(length=100),
        'func': VARCHAR(length=256),
        'hook': VARCHAR(length=256),
        'started': TIMESTAMP(timezone=True),
        'stopped': TIMESTAMP(timezone=True),
        'success': SMALLINT,
        'id': VARCHAR(length=32),
        'group': VARCHAR(length=100),
    },
    'django_session': {
        'session_key': VARCHAR(length=40),
        'expire_date': TIMESTAMP(timezone=True),
    },
    'events': {
        'title': VARCHAR(length=250),
        'start_date': TIMESTAMP(timezone=True),
        'end_date': TIMESTAMP(timezone=True),
        'url': VARCHAR(length=1000),
        'status': SMALLINT,
    },
    'expert_trader_reference_links': {
        'title': VARCHAR(length=1000),
        'link': VARCHAR(length=1000),
        'priority': SMALLINT,
        'status': SMALLINT,
    },
    'expert_traders': {
        'first_name': VARCHAR(length=500),
        'last_name': VARCHAR(length=500),
        'listing_image': VARCHAR(length=500),
        'listing_background': VARCHAR(length=500),
        'detail_image': VARCHAR(length=500),
        'detail_background_image': VARCHAR(length=500),
        'insta_link': VARCHAR(length=1000),
        'facebook_link': VARCHAR(length=1000),
        'linkedin_link': VARCHAR(length=1000),
        'detail_page_first_heading': VARCHAR(length=1000),
        'detail_page_second_heading': VARCHAR(length=1000),
        'detail_page_third_heading': VARCHAR(length=1000),
        'detail_page_first_content': VARCHAR(length=1000),
        'detail_page_second_content': VARCHAR(length=1000),
        'detail_page_third_content': VARCHAR(length=1000),
        'priority': SMALLINT,
        'status': SMALLINT,
    },
    'expert_traders_blogs': {
        'title': VARCHAR(length=250),
        'image': VARCHAR(length=500),
        'priority': SMALLINT,
        'status': SMALLINT,
    },
    'expert_traders_news_articles': {
        'title': VARCHAR(length=250),
        'image': VARCHAR(length=500),
        'media_image': VARCHAR(length=500),
        'media_name': VARCHAR(length=500),
        'interviewed_by': VARCHAR(length=500),
        'link': VARCHAR(length=1000),
        'priority': SMALLINT,
        'status': SMALLINT,
    },
    'expert_traders_videos': {
        'title': VARCHAR(length=250),
        'image': VARCHAR(length=500),
        'videos': VARCHAR(length=1000),
        'priority': SMALLINT,
        'status': SMALLINT,
    },
    'failed_jobs': {
        'id': BIGINT,
        'failed_at': TIMESTAMP,
    },
    'faq_pages': {
        'question': VARCHAR(length=1000),
        'priority': SMALLINT,
        'status': SMALLINT,
    },
    'feed_post_search_key': {
        'id': BigInteger,
        'user_id': BigInteger,
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
    },
    'financial_management_course_videos': {
        'video_id': VARCHAR(length=255),
        'name': VARCHAR(length=255),
        'description': VARCHAR(length=500),
        'video_filename': VARCHAR(length=255),
        'original_video_file_name': VARCHAR(length=255),
        'thumbnail_image': VARCHAR(length=255),
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
        'deleted_at': TIMESTAMP(timezone=True),
    },
    'financial_management_video_progress': {
        'video_id': VARCHAR(length=255),
        'is_complete': SMALLINT,
        'started_at': TIMESTAMP(timezone=True), 
    },
    'financial_question_options': {
        'option_id': VARCHAR(length=255),
        'option': VARCHAR(length=255),
        'deleted_at': TIMESTAMP,
    },
    'financial_questions': {
        'question_id': VARCHAR(length=255),
        'question': VARCHAR(length=255),
        'type': SMALLINT,
        'hint': VARCHAR(length=255),
        'default_value': VARCHAR(length=255),
        'placeholder': VARCHAR(length=255),
        'answer': VARCHAR(length=255),
        'range_min': Integer,
        'range_max': Integer,
    },
    'financial_user_answers': {
        'user_id': VARCHAR(length=255),
        'financial_questions_id': VARCHAR(length=255),
        'financial_question_options_id': VARCHAR(length=255),
    },
    'home_aboutus': {
        'title': VARCHAR(length=500),
        'image': VARCHAR(length=500),
        'background_image': VARCHAR(length=500),
        'link': VARCHAR(length=1000),
    },
    'home_mentors': {
        'image': VARCHAR(length=500),
        'background_image': VARCHAR(length=500),
        'link': VARCHAR(length=1000),
    },
    'image_settings': {
        'id': BIGINT,
        'title': VARCHAR(length=250),
        'value': VARCHAR(length=250),
    },
    'indexed_feed_data': {
        'data_id': VARCHAR(length=250),
        'user_id': VARCHAR(length=250), #Cannot be defined as BigInteger in Database
        # 'user_id': BigInteger,
        # 'user_id': Text,
        'existing_post': VARCHAR(length=250),
        'image': VARCHAR(length=250),
        'video': VARCHAR(length=250),
        'is_shared_post': SMALLINT,
    },
    'indicator_packages': {
        'package_name': VARCHAR(length=100),
        'price': Double,
        'created_by': VARCHAR(length=191),
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
    },
    'invalid_domain': {
        'domain_name': VARCHAR(length=45),
        'last_incident': TIMESTAMP(timezone=True),
        'created_at': TIMESTAMP(timezone=True),
    },
    'invalid_users': {
        'email': VARCHAR(length=45),
        'ip': VARCHAR(length=45),
        'country': VARCHAR(length=45),
        'created_at': TIMESTAMP(timezone=True),
    },
    'investing_course_orders': {
        'transaction_id': VARCHAR(length=255),
        'status': VARCHAR(length=255),
        'payer_email': VARCHAR(length=255),
        'payer_id': VARCHAR(length=255),
        'payer_first_name': VARCHAR(length=255),
        'payer_last_name': VARCHAR(length=255),
        'currency': VARCHAR(length=255),
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
    },
    'investing_course_videos': {
        'video_id': VARCHAR(length=255),
        'name': VARCHAR(length=255),
        'description': VARCHAR(length=255),
        'video_filename': VARCHAR(length=255),
        'original_video_file_name': VARCHAR(length=255),
        'thumbnail_image': VARCHAR(length=255),
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
        'deleted_at': TIMESTAMP(timezone=True),
    },
    'investing_videos_progress': {
        'video_id': VARCHAR(length=255),
        'is_complete': SMALLINT,
        'started_at': TIMESTAMP(timezone=True),
    },
    'language': {
        'language': VARCHAR(length=250),
    },
    'lead_students': {
        'display_name': VARCHAR(length=500),
        'bio': Text,
        'image': VARCHAR(length=500),
        'inner_user_image': VARCHAR(length=500),
        'background_image': VARCHAR(length=500),
        'insta_link': VARCHAR(length=1000),
    },
    'lesson_discussion_forum': {
        'id': BigInteger,
        'user_id': BigInteger,
        'lesson_id': BigInteger,
        'user_name': VARCHAR(length=250),
        'parent_id': BigInteger,
        'top_question_id': BigInteger,
        'tags': VARCHAR(length=500),
        'question_type': Integer, #Based on assumption
        'level': Integer,
        'reply_status': SMALLINT,
        'view_count': BigInteger,
        'created_by': BigInteger,
        'updated_by': BigInteger,
        'created_at': BigInteger,
        'updated_at': BigInteger,
    },
    'lesson_progress': {
        'progress': VARCHAR(length=150),
        'completed': SMALLINT,
    },
    'lessons': {
        'name': VARCHAR(length=500),
        'slug': VARCHAR(length=200),
        'video': VARCHAR(length=500),
        'video_time': VARCHAR(length=150),
        'video_thumbnails': VARCHAR(length=500),
        'video_banner_image': VARCHAR(length=100),
    },
    'library_faq': {
        'id': BigInteger,
        'user_id': BigInteger,
        'parent_id': BigInteger,
        'top_question_id': BigInteger,
        'title': VARCHAR(length=250),
        'tags': VARCHAR(length=500),
        'question_type': Integer,
        'level': Integer,
        'view_count': BigInteger,
        'created_by': BigInteger,
        'updated_by': BigInteger,
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
    },
    'market_calls': {
        'title': VARCHAR(length=500),
        'date': Date,
        'market': VARCHAR(length=500),
        'income_type': VARCHAR(length=500),
        'image': VARCHAR(length=250),
        'user_image': VARCHAR(length=250),
        'video': VARCHAR(length=500),
    },
    'market_review': {
        'topic': VARCHAR(length=500),
        'short_description': VARCHAR(length=500),
        'image': VARCHAR(length=150),
        'show_date': Date,
    },
    'market_timing_orientation_online_form': {
        'id': BigInteger,
        'user_id': BigInteger,
        'name': VARCHAR(length=250),
        'email': VARCHAR(length=250),
        'phone_number': VARCHAR(length=250),
        'created_at': BigInteger,
        'updated_at': BigInteger,
        'created_by': BigInteger,
        'updated_by': BigInteger,
    },
    'market_timings': {
        'title': VARCHAR(length=500),
        'video': VARCHAR(length=500),
        'video_thumbnail': VARCHAR(length=500),
        'video_thumbnail_banner': VARCHAR(length=100),
        'video_time': VARCHAR(length=100),
        'slug': VARCHAR(length=200),
    },
    'mentor': {
        'expertise': VARCHAR(length=250),
        'price': DOUBLE_PRECISION(11,4),
    },
    'mentor_contact': {
        'price': DOUBLE_PRECISION(11,4),
        'mentor_response_status': SMALLINT,
        'meeting_status': SMALLINT,
        'payment_status': SMALLINT,
        'transaction_id': VARCHAR(length=500),
        'payment_mode': VARCHAR(length=500),
        'payment_date': TIMESTAMP(timezone=True),
        'webinar_host': VARCHAR(length=255),
    },
    'mentor_contact_details': {
        'date': Date,
        'from_time': Interval,
        'to_time': Interval,
        'utc_date': Date,
        'utc_from_time': Interval,
        'utc_to_time': Interval,
        'approval': SMALLINT,
    },
    'mentor_rating': {
        'rating': DECIMAL(10,0),  
    },
    'mentor_webinar_details': {
        'date': Date,
        'from_time': Interval,
        'to_time': Interval,
        'class_room_id': VARCHAR(length=250),
        'video_banner_image': VARCHAR(length=255),
        'video_thumbnail': VARCHAR(length=255),
        'video_file': VARCHAR(length=255),
        'duration': VARCHAR(length=255),
    },
    'mentor_webinar_details_launch_url': {
        'class_room_id': VARCHAR(length=250),
        'video': VARCHAR(length=500),
        'is_teacher': SMALLINT,
    },
    'migration': {
        'version': VARCHAR(length=180),
        'apply_time': Integer,
    },
    'migrations': {
        'migration': VARCHAR(length=191),
    },
    'modules_progress': {
        'completed': SMALLINT,
    },
    'new_notifications': {
        'notification_type': VARCHAR(length=20),
        'notification_action': VARCHAR(length=20),
        'url': VARCHAR(length=255),
        'is_read': Boolean,
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
    },
    'notes': {
        'title': VARCHAR(length=500),
        'short_description': VARCHAR(length=1000),
        'description': Text,
    },
    'notes_attachment': {
        'file': VARCHAR(length=250),
        'file_name': VARCHAR(length=250),
    },
    'notificaitons_emails': {
        'sent': SMALLINT,
        'from_id': VARCHAR(length=255),
        'post_id': VARCHAR(length=255),
        'subject': VARCHAR(length=255),
        'body': VARCHAR(length=255),
    },
    'notification': {
        'show_date': TIMESTAMP(timezone=True),
        'entity_name': VARCHAR(length=250),
        'email_notification': VARCHAR(length=1), #Based on assumption
    },
    'notification_summary': {
        'id': BigInteger,
        'entity_type': Integer,
        'entity_id': BigInteger,
        'description': VARCHAR(length=1000),
        'show_date': TIMESTAMP(timezone=True),
    },
    'notifications_browser': {
        'id': BigInteger,
        'sent': SMALLINT,
        'from_id': VARCHAR(length=255),
        'post_id': VARCHAR(length=255),
        'subject': VARCHAR(length=255),
        'body': VARCHAR(length=255),
    },
    'otc_report_scheduler': {
        'id': VARCHAR(length=11),
        'criteria': VARCHAR(length=250),
        'params': VARCHAR(length=250),
        'schedule_time': Interval,
        'schedule_date': TIMESTAMP(timezone=True),
        'next_run_day': TIMESTAMP(timezone=True),
        'next_run_time': Interval,
    },
    'packages': {
        'slug': VARCHAR(length=250),
        'title': VARCHAR(length=100),
        'features': Text,
        'courses': VARCHAR(length=250),
        'price': VARCHAR(length=250),
        'discount': VARCHAR(length=250),
        'offer_price': VARCHAR(length=250),
        # 'validity': Date, #Needs to be Date, Can't be done currently as 0000-00-00 entries exist
        'image': VARCHAR(length=250),
        'installment_available': SMALLINT,
    },
    'page': {
        'slug': VARCHAR(length=250),
        'title': VARCHAR(length=100),
        'image': VARCHAR(length=100),
        'next_page_id': Integer,
        'previous_page_id': Integer,
    },
    'password_resets': {
        'email': VARCHAR(length=191),
        'token': VARCHAR(length=191),
        'created_at': TIMESTAMP(timezone=True),
    },
    'personality_test': {
        'id': BigInteger, # Also happens to be the only field here, this may not be required
    },
    'personality_test_answers': {
        'section_name': VARCHAR(length=250),
        'next_section': VARCHAR(length=100),
    },
    'products': {
        'product_code': VARCHAR(length=250),
        'product_name': VARCHAR(length=250),
    },
    'quiz_questions': {
        'id': BigInteger,
        'unique_id': BigInteger,
        'course_id': BigInteger,
        'subject_id': BigInteger,
        'lesson_id': BigInteger,
        'created_by': BigInteger,
        'updated_by': BigInteger,
        'created_at': BigInteger,
        'updated_at': BigInteger,
    },
    'quiz_questions_details': {
        'id': BigInteger,
        'unique_id': BigInteger,
        'question': Text,
        'option_a': VARCHAR(length=500),
        'option_b': VARCHAR(length=500),
        'option_c': VARCHAR(length=500),
        'option_d': VARCHAR(length=500),
        'correct_ans': VARCHAR(length=50),
        'created_by': BigInteger,
        'updated_by': BigInteger,
        'created_at': BigInteger,
        'updated_at': BigInteger,
    },
    'ratings': {
        'review': Text,
        'redirect_to_trustpilot': Boolean,
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
    },
    'recordings_courses': {
        'name': VARCHAR(length=500),
        'slug': VARCHAR(length=200),
        'short_description': Text,
        'description': Text,
        'image': VARCHAR(length=500),

    },
    'recordings_lessons': {
        'name': VARCHAR(length=500),
        'slug': VARCHAR(length=200),
        'short_description': Text,
        'description': Text,
        'image': VARCHAR(length=500),

    },
    'recordings_modules': {
        'name': VARCHAR(length=500),
        'slug': VARCHAR(length=200),
        'description': Text,
        'image': VARCHAR(length=500),
    },
    'reported_entities': {
        'entity_type': VARCHAR(length=191),
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
    },
    'retirement_planning_comments': {
        'user_name': VARCHAR(length=45),
        'user_image': VARCHAR(length=255),
        'image_id': BigInteger,
    },
    'sat_discussion_forum': {
        'id': BigInteger,
        'user_id': BigInteger,
        'sat_id': BigInteger,
        'user_name': VARCHAR(length=250),
        'parent_id': BigInteger,
        'top_question_id': BigInteger,
        'question': Text,
        'tags': VARCHAR(length=500),
        'question_type': Integer,
        'level': Integer,
        'status': SMALLINT,
        'created_by': BigInteger,
        'updated_by': BigInteger,
        'created_at': BigInteger,
        'updated_at': BigInteger,
    },
    'seo_meta_tags': {
        'description': VARCHAR(length=500),
    },
    'settings': {
        'created_at': BigInteger,
        'updated_at': BigInteger,
        'created_by': BigInteger,
        'updated_by': BigInteger,
    },
    'student_courses': {
        'eligible_courses': VARCHAR(length=500),
        'price': DOUBLE_PRECISION(11,4),
        'transaction_id': VARCHAR(length=500),
        'payment_mode': VARCHAR(length=500),
        'payment_date': TIMESTAMP(timezone=True),
    },
    'student_courses_status': {
        'course_name': VARCHAR(length=250),
        'completed_modules': VARCHAR(length=250),
        'completed_lessons': VARCHAR(length=250),
        'completed_quiz_lesson_ids': VARCHAR(length=500),
        'time': VARCHAR(length=250),
        'status': Enum(StudentCoursesStatusStatusEnum),
        'has_badge': SMALLINT,
        'badge_image': VARCHAR(length=200),

    },
    'student_questions': {
        'title': VARCHAR(length=500),
        'image': VARCHAR(length=250),
        'question_type': SMALLINT,
        'status': SMALLINT,
        'reply_status': SMALLINT,
    },
    'student_trade_review': {
        'student_name': VARCHAR(length=250),
        'trade_success': SMALLINT,
        'keep_anonymous': SMALLINT,
        'style': VARCHAR(length=250),
        'trade_type': VARCHAR(length=250),
        'symbol': VARCHAR(length=250),
        'market': VARCHAR(length=250),
        'admin_approval': SMALLINT,
        'review_date': Date,
        'review_time_from': Interval,
        'review_time_to': Interval,
        'time_slot': VARCHAR(length=250),
    },
    'student_trade_review_images': {
        'image': VARCHAR(length=250),
    },
    'subject': {
        'course_id': VARCHAR(length=100),
        'name': VARCHAR(length=500),
        'image': VARCHAR(length=500),
        'icon': VARCHAR(length=100),
        'video': VARCHAR(length=500),
        'video_time': VARCHAR(length=150),
        'slug': VARCHAR(length=200),
        'language_id': BigInteger,
    },
    'subject_discussion_forum': {
        'user_name': VARCHAR(length=250),
        'tags': VARCHAR(length=500),
        'question_type': SMALLINT,
        'level': Integer,
        'reply_status': SMALLINT,
    },
    'system_notification': {
        'notification_id': VARCHAR(length=255),
        'entity': VARCHAR(length=255),
        'title': VARCHAR(length=255),
        'status': SMALLINT,
        'send_email': SMALLINT,
        'send_sms': SMALLINT,
        'send_browser_notification': SMALLINT,
        'email_sent_at': TIMESTAMP(timezone=True),
        'sms_sent_at': TIMESTAMP(timezone=True),
        'browser_notification_sent_at': TIMESTAMP(timezone=True),
    },
    'text_block': {
        'title': VARCHAR(length=200),
        'home_image': VARCHAR(length=250),
    },
    'trade_plan': {
        'stop_level': VARCHAR(length=250),
        'stop_size': VARCHAR(length=250),
        'entry_one_level': VARCHAR(length=250),
        'entry_one_size': VARCHAR(length=250),
        'entry_two_level': VARCHAR(length=250),
        'entry_two_size': VARCHAR(length=250),
        'target_one_level': VARCHAR(length=250),
        'target_one_size': VARCHAR(length=250),
        'target_two_level': VARCHAR(length=250),
        'target_two_size': VARCHAR(length=250),
        'enhancer_score': Integer, #Might be ok with SMALLINT
    },
    'trading_performance': {
        'image': VARCHAR(length=500),
    },
    'user': {
        'id': BIGINT,
        'status': SMALLINT,
        'username': VARCHAR(length=255),
        'first_name': VARCHAR(length=200),
        'last_name': VARCHAR(length=200),
        'auth_key': VARCHAR(length=32),
        'password_hash': VARCHAR(length=255),
        'password_reset_token': VARCHAR(length=255),
        'email': VARCHAR(length=255),
        'user_photo': VARCHAR(length=150),
        'phone_number': VARCHAR(length=255),
        'facebook_id': BIGINT,
        'date': TIMESTAMP(timezone=True),
        'time_zone': VARCHAR(length=1000),
        'eligible_for_installment': Integer,
        'session_id': VARCHAR(length=500),
        'destroy_session': Integer,
        'synchronize': Integer,
        'user_type': Integer,
        'ip': VARCHAR(length=255),
        'superadmin': SMALLINT,
        'is_blocked': SMALLINT,
        'is_deleted': SMALLINT,
        'unique_id': VARCHAR(25),
        'totp_login_id': VARCHAR(255),
        'otl_session_id': VARCHAR(255),
        'need_to_change_username':  Boolean, 
        'from_third_party': Boolean, 
    },
    'user_connection_details': {
        'request_sent_or_received_time': TIMESTAMP(timezone=True),
        'request_accepted_or_approved_time': TIMESTAMP(timezone=True),
        'blocked_person': Integer, #Could use testing
        'request_cancelled_time': TIMESTAMP(timezone=True),
        'request_cancelled_user_id': BigInteger,
    },
    'user_market_timing_orientation': {
        'viewed_market_timings': VARCHAR(length=250),
        'status': Enum(UserMarketTimingOrientationStatusEnum),
        'time': VARCHAR(length=250),
    },
    'user_message': {
        'id': BigInteger,
        'user_id': BigInteger,
        'title': VARCHAR(length=500),
    },
    'user_post_comments': {
        'user_name': VARCHAR(length=250),
        'user_image': VARCHAR(length=250),
        'image': VARCHAR(length=255),
    },
    'user_post_files': {
        'file': VARCHAR(length=100),
        'file_type': VARCHAR(length=50),
        'created_at': TIMESTAMP(timezone=True),
        'updated_at': TIMESTAMP(timezone=True),
        'file_name': VARCHAR(length=250),
    },
    'user_post_share': {
        'original_post_user_name': VARCHAR(length=250),
        'original_image': VARCHAR(length=250),
        'original video': VARCHAR(length=255),
    },
    'user_posts': {
        'image': VARCHAR(length=250),
        'video': VARCHAR(length=255),
    },
    'user_profile': {
        'address': VARCHAR(length=500),
        'street': VARCHAR(length=1000),
        'company': VARCHAR(length=250),
        'pin_code': Integer,
        'state': VARCHAR(length=150),
        'city': VARCHAR(length=250),
        'latitude': VARCHAR(length=100),
        'longitude': VARCHAR(length=100),
        'country': VARCHAR(length=150),
        'telephone': Integer,
        'banner_image': VARCHAR(length=200),
        'sat_score': Double,
        'instagram_link': VARCHAR(length=1000),
    },
    'user_profile_settings': {
        'show_my_username_to_others': VARCHAR(length=1),
        'shown_sat_score_for_me': Enum(enum.Enum('user_profile_settings_shown_sat_score_for_me_enum', {'All': 1, 'Connections': 2, 'null': 3, 'None': 4})),
        'shown_friends_post_for_me': Enum(enum.Enum('user_profile_settings_shown_friends_post_for_me_enum', {'All': 1, 'Connections': 2, 'null': 3, 'None': 4})),
        'shown_calender': Enum(enum.Enum('user_profile_settings_shown_calender_enum', {'All': 0, 'None': 1})),
        'shown_daily_market_overview': VARCHAR(length=1),
        'shown_news_alert': VARCHAR(length=1),
        'shown_otc_new_joins': VARCHAR(length=1),
        'show_my_sat_score_to_others': Enum(enum.Enum('user_profile_settings_show_my_sat_score_to_others_enum', {'All': 1, 'Connections': 2, 'null': 3, 'None': 4})),
        'show_my_post_to_others': Enum(enum.Enum('user_profile_settings_show_my_post_to_others_enum', {'All': 1, 'Connections': 2, 'null': 3, 'None': 4})),
        'sharing_sat_score': VARCHAR(length=1),
        'sharing_posts': VARCHAR(length=1),
        'browser_notification': VARCHAR(length=1),
        'email_notification': VARCHAR(length=1),
    },
    'user_progress': {
        'step_one_complete': SMALLINT,
        'allow_user': SMALLINT,
        'step_two_complete': SMALLINT,
        'step_three_complete': SMALLINT,
        'step_four_complete': SMALLINT,
        'step_one_started_at': TIMESTAMP(timezone=True),
        'step_two_started_at': TIMESTAMP(timezone=True),
        'step_three_started_at': TIMESTAMP(timezone=True),
        'is_paid': SMALLINT,
        'step_four_started_at': TIMESTAMP(timezone=True),
        'step_three_ended_at': TIMESTAMP(timezone=True),
        'booking_id': BigInteger,
        'reschedule': SMALLINT,
        'call_complete': SMALLINT,
        'invoice_uploaded': SMALLINT,
        'payment_proof': VARCHAR(length=255),
        'invoice_no': BigInteger,
        'issue_date': Date,
        'due_date': Date,
        'investing_video_course_completed_at': TIMESTAMP(timezone=True),
        'financial_management_video_course_completed_at': TIMESTAMP(timezone=True),
    },
    'user_quiz_answers': {
        'id': BigInteger,
        'user_id': BigInteger,
        'course_id': BigInteger,
        'lesson_id': BigInteger,
        'module_id': BigInteger,
        'question_id': BigInteger,
        'answer': VARCHAR(length=20),
        'actual_answer': VARCHAR(length=100),
        'question_answer': VARCHAR(length=500),
        'created_by': BigInteger,
        'updated_by': BigInteger,
        'created_at': BigInteger,
        'updated_at': BigInteger,
    },
    'user_sat': {
        'time': Enum(enum.Enum('user_sat_time_enum', {'High Frequency': 0, 'Hourly Income': 1, 'Daily Income': 2, 'Weekly Income': 3, 'Monthly Income': 4})),
        'trade_type': VARCHAR(length=1),
        'target_one': VARCHAR(length=250),
        'target_two': VARCHAR(length=250),
        'target_three': VARCHAR(length=250),
        'entry': VARCHAR(length=250),
        'stop': VARCHAR(length=250),
        'time_frame': VARCHAR(length=250),
        'synchronize': SMALLINT,
    },
    'user_sat_favorites': {
        'id': BigInteger,
        'user_id': BigInteger,
        'sat_id': BigInteger,
        'status': SMALLINT,
        'created_by': BigInteger,
        'updated_by': BigInteger,
        'created_at': BigInteger,
        'updated_at': BigInteger,
    },
    'user_sat_images': {
        'image': VARCHAR(length=250),
    },
    'user_sat_summary': {
        'id': BigInteger,
        'user_id': BigInteger,
        'trades_posted': BigInteger,
        'trades_executed': BigInteger,
        'successfull_trades': BigInteger,
        'win_ratio': VARCHAR(length=250),
        'loss_ratio': VARCHAR(length=250),
        'risk_ratio': VARCHAR(length=250),
        'reward_ratio': VARCHAR(length=250),
        'efficiency_score': VARCHAR(length=250),
        'frequency_score': VARCHAR(length=250),
        'price': VARCHAR(length=250),
        'created_by': BigInteger,
        'updated_by': BigInteger,
        'created_at': BigInteger,
        'updated_at': BigInteger,
    },
    'user_subject': {
        'id': BigInteger,
        'user_id': BigInteger,
        'subject_id': BigInteger,
        'subject_status': VARCHAR(length=500),
        'video_time': VARCHAR(length=500),
        'created_by': BigInteger,
        'updated_by': BigInteger,
        'created_at': BigInteger,
        'updated_at': BigInteger,
    },
    'user_tokens': {
        'user_id': BigInteger, #Originally set as VARCHAR(length=255)
        'browser': VARCHAR(length=255),
    },
    'user_totp': {
        'secret': VARCHAR(length=255),
        'created_at': TIMESTAMP,
        'updated_at': TIMESTAMP,
    },
    'user_mentions': {
        'created_at': BigInteger,
        'updated_at': BigInteger,
    },
    'verified_phones': {
        'user_id': VARCHAR(length=255),
        'otp': VARCHAR(length=255),
        'expires_at': TIMESTAMP(timezone=True),
    },
    'zoom_webinars': {
        'entity': VARCHAR(length=255),
        'host_id': VARCHAR(length=255),
        'topic': VARCHAR(length=255),
        'status': VARCHAR(length=255),
        'start_time': TIMESTAMP(timezone=True),
        'timezone': VARCHAR(length=255),
        'agenda': VARCHAR(length=255),
        'meeting_created': TIMESTAMP(timezone=True),
        'password': VARCHAR(length=255),
        'h323_password': VARCHAR(length=255),
        'pstn_password': VARCHAR(length=255),
        'created_at': TIMESTAMP(timezone=True),
    },
}

# These data types will be applied to all tables if the column also exists, otherwise it is ignored
# WARNING: If even one of these data types for one of the tables is wrong, the table will default back to its original data type definition
default_data_types = {
    'priority': SMALLINT,
    'status': SMALLINT,
    'deleted_at': TIMESTAMP(timezone=True),
}

# In case you do not want to add the global data types to specific tables
excluded_tables = []

for table in custom_data_types:
    for column in default_data_types:
        if column not in custom_data_types[table] and table not in excluded_tables:
            custom_data_types[table][column] = default_data_types[column]