#!/usr/bin/python3
"""Purpose: Exports the constraints and indexes from MySQL Database into Postgresql database

Additional References
https://stackoverflow.com/questions/2204058/list-columns-with-indexes-in-postgresql - List the indexes of a table along with their respective columns
"""

import os
from io import TextIOWrapper
from timeit import default_timer

from sqlalchemy import URL, MetaData, Engine, Table, create_engine, text, ForeignKey, Index, Inspector, inspect
from dotenv import load_dotenv


def make_identity(postgres_connection: Engine, table_name: str, serial_col: str = 'id'):
    """Sets up identity columns for given primary key columns"""

    try:
        query = f"ALTER TABLE public.\"{table_name}\" ALTER \"{serial_col}\" ADD GENERATED BY DEFAULT AS IDENTITY"
        restart_query = f"SELECT setval(pg_get_serial_sequence('\"public\".\"{table_name}\"', '{serial_col}'), (SELECT MAX(\"{serial_col}\") FROM public.\"{table_name}\"))"
        with postgres_connection.connect() as conn:
            conn.execute(text(query))
            conn.commit()
            conn.execute(text(restart_query)) #Sets new value to max
            conn.commit()
            print(f"Column {serial_col} of table {table_name} set as identity column")
    except Exception as e: 
        print(f"Error encountered while trying to set identity column for column {serial_col} of table {table_name}: {e}")


def make_sequence(postgres_connection: Engine, table_name: str, serial_col: str = 'id'):
    """Sets up Sequences for table primary key
    
    Note: This function should no longer be required, it is only here in case using the make_identity function does not work out....
    """

    # In case we need to set autoincrement for other columns, refer to this documentation: 
    # https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Column.params.autoincrement

    try:
        with postgres_connection.connect() as con:
            sequence_name = f"{table_name}_{serial_col}_seq"

            # Create a sequence obj for the serial column
            query = f"CREATE SEQUENCE {sequence_name}"
            con.execute(text(query))
            con.commit()

            # Alter table to use the new sequence object
            query = f"ALTER TABLE public.\"{table_name}\" ALTER COLUMN \"{serial_col}\" SET DEFAULT nextval('{sequence_name}')"
            con.execute(text(query))
            con.commit()

            # Alter sequence to be owned by table serial_col
            query = f"ALTER SEQUENCE {sequence_name} OWNED BY public.\"{table_name}\".\"{serial_col}\""
            con.execute(text(query))
            con.commit()

            # Set sequence value 
            query = f"SELECT setval('{sequence_name}', (SELECT COALESCE(MAX(\"{serial_col}\"), 1) FROM public.\"{table_name}\"))"
            # query = f"SELECT setval('{sequence_name}', (SELECT MAX({serial_col}) FROM public.{table_name}))"
            con.execute(text(query))
            con.commit()

            print(f"Column {serial_col} of table {table_name} set as sequence")
    except Exception as e:
        print(f"Error encountered while trying to add sequence to column {serial_col} of table {table_name}: {e}")


def set_not_null(postgres_connection: Engine, table_metadata: Table):
    """Sets Columns in Postgresql Database to Not Null if they are Not Null in MySQL Database"""
    
    with postgres_connection.connect() as conn:
        for column in table_metadata.columns:
            if not column.nullable:
                # Setting Column values from NULL to empty string if NULL values exist (this can happen when importing from csv files)
                query = f'SELECT "{column.name}" FROM public.\"{table_metadata.name}\" WHERE "{column.name}" IS NULL'
                result = conn.execute(text(query))
                if len(result.fetchall()) > 0:
                    print(f"WARNING: Possible null values in column {column.name} of table {table_metadata.name}")
                    try:
                        if str(column.type) != 'ENUM':
                            query = f"UPDATE public.\"{table_metadata.name}\" SET \"{column.name}\" = '' WHERE \"{column.name}\" IS NULL"
                        else:
                            print("Enum detected, setting Null value to None string, change this in script if this is not working")
                            query = f"UPDATE public.\"{table_metadata.name}\" SET \"{column.name}\" = 'None' WHERE \"{column.name}\" IS NULL"
                        conn.execute(text(query))
                        conn.commit()
                        print(f"Null values changed to empty strings in column {column.name} of table {table_metadata.name}")
                    except Exception as e:
                        print(f"Error encountered while trying to change NULL values to empty string in column {column.name} for table {table_metadata.name}: {e}")
                        conn.rollback()
                        print("Successfully rolled back error query")

                try:
                    query = f'ALTER TABLE public.\"{table_metadata.name}\" ALTER COLUMN "{column.name}" SET NOT NULL'
                    conn.execute(text(query))
                    conn.commit()
                    print(f"Column {column.name} of table {table_metadata.name} set to NOT NULL")
                
                except Exception as e:
                    print(f"Error encountered while setting NOT NULL for column {column.name} of table {table_metadata.name}: {e}")
                    conn.rollback()
                    print("Successfully rolled back error query")
                    continue


def set_defaults(postgres_connection: Engine, mysql_connection: Engine, table_name: str):
    # There probably is a better way, but this way works for now

    # Creating dictionary to map columns to any default values found
    defaults = {}
    with mysql_connection.connect() as conn:
        query = f"SHOW FULL COLUMNS FROM `{table_name}`"
        column_definitions = conn.execute(text(query)).fetchall()
        for column_definition in column_definitions:
            # In the results, default value is in index 5
            if column_definition[5] is not None:
                defaults[column_definition[0]] = column_definition[5]

    excluded_defaults = ['CURRENT_TIMESTAMP']

    if len(defaults) > 0:
        with postgres_connection.connect() as conn:
            for column_name, default_value in defaults.items():
                try:
                    query = f'ALTER TABLE public.\"{table_name}\" ALTER COLUMN \"{column_name}\" SET DEFAULT '
                    query += f'{default_value}' if default_value.isnumeric() or default_value in excluded_defaults else f"'{default_value}'" 
                    conn.execute(text(query))
                    conn.commit()
                    print(f"Column {column_name} of table {table_name} set to use default value {default_value}")
                except Exception as e:
                    print(f"Error encountered while setting default value {default_value} for column {column_name} of table {table_name}: {e}")
                    conn.rollback()
                    print("Successfully rolled back error query")
                    continue


def quotify_columns(columns: list[str]) -> list[str]:
    """Adding quotes to column names to maintain case"""

    return ['"' + column + '"' for column in columns]


def export_additional(mysql_connection: Engine, postgres_connection: Engine, metadata: MetaData, table_name: str, inspect_obj: Inspector = None):
    # Load the table schema from MySQL to get constraints
    table_metadata = Table(table_name, metadata, autoload_with=mysql_connection)

    with postgres_connection.connect() as con:
        # Create primary key constraints in PostgreSQL
        if table_metadata.primary_key:
            pk_cols = []
            for pk in table_metadata.primary_key.columns:
                pk_cols.append(pk.name)

            pk_name = f"{table_name}_pk_"
            for pk_col in pk_cols:
                pk_name += f"{pk_col}_"
            try:
                statement = f"ALTER TABLE public.\"{table_name}\" ADD CONSTRAINT {pk_name[:-1]} PRIMARY KEY ({','.join(quotify_columns(pk_cols))})"
                con.execute(text(statement))
                con.commit()
                print(f"Primary Key Constraint {table_name}_pk added to table {table_name}")
            except Exception as e:
                print(f"Error while setting primary key constraint for table {table_name}: {e}")
                con.rollback()
                print("Successfully rolled back error query")


        # Adding auto increment feature....
        if table_metadata.primary_key:
            for pk in table_metadata.primary_key.columns:
                # Using Identity Columns
                # Reference: https://stackoverflow.com/questions/55555547/how-can-i-change-an-existing-column-to-identity-in-postgresql-11-1
                if str(pk.type) in ('INTEGER','BIGINT'):            
                    make_identity(postgres_connection, table_name, pk.name)
                else:
                    print(f"Primary key {pk.name} of table {table_name} is not integer or big integer, not setting this as an identity column, please verify this: TYPE {pk.type}")

                # # Also, using sequences, in case identity is not created successfully or any other errors
                # # Reference: https://stackoverflow.com/questions/9490014/adding-serial-to-existing-column-in-postgres
                # make_sequence(postgres_connection, table_name, pk.name)
                
        # Adding Unique Key Constraints
        if inspect_obj is not None and checkUniqueConstraints(inspect_obj, table_name):
            for unique_constraint in inspect_obj.get_unique_constraints(table_name=table_name):
                unique_constraint_name = unique_constraint.get('name')
                unique_constraint_columns = unique_constraint.get('column_names')

                query = text(f"ALTER TABLE public.\"{table_name}\" ADD CONSTRAINT {table_name}_uq_{unique_constraint_name} UNIQUE ({','.join(quotify_columns(unique_constraint_columns))})")

                try:
                    con.execute(query)
                    con.commit()
                    print(f"Unique Key Constraint {table_name}_uq_{unique_constraint_name} added to table {table_name}")
                except Exception as e:
                    print(f"Error encountered while trying to add unique key {unique_constraint_name} to table {table_name}: {e}")
                    con.rollback()
                    print("Successfully rolled back error query")


        # Keeping Note of failed foreign key and index imports
        fk_failed = []
        index_failed = []

        # Migrating foreign key constraints
        for fk in table_metadata.foreign_keys:
            # Get the source and target tables for foreign keys
            source_table = fk.parent.table.name
            target_table = fk.column.table.name
            target_column = fk.column.name
            source_column = fk.parent.name
            on_delete = fk.ondelete if fk.ondelete is not None else 'RESTRICT'
            on_update = fk.onupdate if fk.onupdate is not None else 'RESTRICT'

            # Construct the foreign key constraint SQL
            sql = text(f"ALTER TABLE \"{source_table}\" ADD CONSTRAINT fk_{source_table}_{target_table} FOREIGN KEY (\"{source_column}\") REFERENCES public.\"{target_table}\"(\"{target_column}\") ON DELETE {on_delete} ON UPDATE {on_update}")
            
            try:
                con.execute(sql)
                con.commit()
                print(f"Foreign key {source_column} -> {target_column} added to table {source_table}")
            except Exception as e:
                print(f"Error adding foreign key: {e}")
                con.rollback()
                print("Successfully rolled back error query")
                print("Reattempt will be made to add this foreign key after all tables have been setup")
                fk_failed.append(fk)

        # Migrating other indexes (if any)
        # Should check if extra indexes are being created to save space
        for index in table_metadata.indexes:
            index_columns = ', '.join(quotify_columns(index.columns.keys()))
            query = f"CREATE INDEX {table_name}_idx_{index.name.replace('-','_')} ON public.\"{table_name}\" ({index_columns})"
            if index.unique:
                query = f"CREATE UNIQUE INDEX {table_name}_idx_{index.name.replace('-','_')} ON public.\"{table_name}\" ({index_columns})"
            sql = text(query)
            try:
                con.execute(sql)
                con.commit()
                print(f"Index {table_name}_idx_{index.name.replace('-','_')} added to table {table_name}")
            except Exception as e:
                print(f"Error adding index {index.name}: {e}")
                con.rollback()
                print("Successfully rolled back error query")
                print("Reattempt will be made to add this index after all tables have been setup")
                index_failed.append(index)

        # Setting Table Columns as Not Null
        set_not_null(postgres_connection, table_metadata)

        # Setting Table Column Defaults if exists
        set_defaults(postgres_connection, mysql_connection, table_name)

    return (fk_failed, index_failed)


def checkUniqueConstraints(inspect_obj: Inspector, table_name: str) -> bool:
    return len(inspect_obj.get_unique_constraints(table_name=table_name)) > 0


def reattempt_export_additional(mysql_connection: Engine, postgres_connection: Engine, metadata: MetaData, 
                                table_name: str, fk_failed: list[ForeignKey], index_failed: list[Index], file: TextIOWrapper = None):
    table_metadata = Table(table_name, metadata, autoload_with=mysql_connection)

    print(f"Reattempting foreign key and index exports for table {table_name}")

    status = False

    with postgres_connection.connect() as con:
        # Reattempting foreign key exports
        for index, fk in enumerate(fk_failed):
            # Get the source and target tables for foreign keys
            source_table = fk.parent.table.name
            target_table = fk.column.table.name
            target_column = fk.column.name
            source_column = fk.parent.name
            on_delete = fk.ondelete if fk.ondelete is not None else 'RESTRICT'
            on_update = fk.onupdate if fk.onupdate is not None else 'RESTRICT'
            
            # Construct the foreign key constraint SQL
            sql = text(f"ALTER TABLE \"{source_table}\" ADD CONSTRAINT fk_{source_table}_{target_table}_{index} FOREIGN KEY (\"{source_column}\") REFERENCES public.\"{target_table}\"(\"{target_column}\") ON DELETE {on_delete} ON UPDATE {on_update}")

            try:
                con.execute(sql)
                con.commit()
                print(f"Foreign key {source_column} -> {target_column} added to table {source_table}")
            except Exception as e:
                print(f"Error adding foreign key: {e}")
                con.rollback()
                print("Successfully rolled back error query")

                print("Debug Details: ", source_table, target_table, index, source_column, target_column)

                if file is not None:
                    file.write(f"\n{e}\n")
                    file.write(f"\n**************************************************************************\n")
                    print(f"Error added to log")
                status = True

        # Reattempting additional index exports 
        for index in index_failed:
            index_columns = ', '.join(quotify_columns(index.columns.keys()))
            sql = text(f"CREATE INDEX {table_name}_idx_{index.name.replace('-','_')} ON public.\"{table_name}\" ({index_columns})")
            try:
                con.execute(sql)
                con.commit()
                print(f"Index {table_name}_idx_{index.name.replace('-','_')} added to table {table_name}")
            except Exception as e:
                print(f"Error adding index {index.name}: {e}")
                con.rollback()
                print("Successfully rolled back error query")
                if file is not None:
                    file.write(f"\n{e}\n")
                    file.write(f"\n**************************************************************************\n")
                    print(f"Error added to log")
                status = True

    return status


if __name__ == "__main__":
    execution_start = default_timer()

    load_dotenv()

    # mysql_connection_str = f"mysql+pymysql://{environ['MYSQL_DB_USERNAME']}:{environ['MYSQL_DB_PASSWORD']}@{environ['MYSQL_DB_HOST']}/{environ['MYSQL_DB_DATABASE']}"
    mysql_connection_str = URL.create(
        'mysql+pymysql',
        username=os.environ['MYSQL_DB_USERNAME'],
        password=os.environ['MYSQL_DB_PASSWORD'],
        host=os.environ['MYSQL_DB_HOST'],
        port=os.environ['MYSQL_DB_PORT'],
        database=os.environ['MYSQL_DB_DATABASE']
    )
    mysql_connection = create_engine(mysql_connection_str)

    # Inspecting for unique key constraints
    inspect_obj = inspect(mysql_connection)

    # postgres_connection_str = f"postgresql+psycopg://{environ['PG_DB_USERNAME']}:{environ['PG_DB_PASSWORD']}@{environ['PG_DB_HOST']}:5432/{environ['PG_DB_DATABASE']}"
    postgres_connection_str = URL.create(
        'postgresql+psycopg',
        username=os.environ['PG_DB_USERNAME'],
        password=os.environ['PG_DB_PASSWORD'],
        host=os.environ['PG_DB_HOST'],
        port=os.environ['PG_DB_PORT'],
        database=os.environ['PG_DB_DATABASE'],
    )
    postgres_connection = create_engine(postgres_connection_str)

    metadata = MetaData()

    metadata.reflect(bind=mysql_connection)

    failed_tracker = {} # In case foreign key and index exports are not valid at the beginning

    for table_name in metadata.tables.keys():
        print(f"\nExporting Additional Metadata for table {table_name}")
        fk_failed, index_failed = export_additional(mysql_connection, postgres_connection, metadata, table_name, inspect_obj)
        print(f"Additional Metadata for table {table_name} has been exported",end="\n")
        if len(fk_failed) > 0 or len(index_failed) > 0:
            failed_tracker[table_name] = (fk_failed, index_failed)

    print("\nReattempting Foreign Key and Index Exports for the following tables:",",".join(list(failed_tracker.keys())),end="\n\n")

    reattempt_error_status = False

    file = open(os.path.join(os.path.abspath(os.path.realpath(__file__).replace(os.path.basename(__file__),"")),'errors.log'), "a")
    file.write("Errors encountered when exporting foreign keys and indexes to Postgres Database\n")

    # Reattempting to reimport foreign keys after initial failure
    if len(failed_tracker) > 0:
        for table_name in failed_tracker.keys():
            status = reattempt_export_additional(mysql_connection,postgres_connection,metadata,table_name,failed_tracker[table_name][0],failed_tracker[table_name][1],file)
            if status and not reattempt_error_status:
                reattempt_error_status = True

    file.close()

    print("All constraints and indexes successfully migrated from MySQL to Postgresql. NOTE: Please check out database for any further tweaks")
    if reattempt_error_status:
        print("Errors encountered in reattempt effort, please check out the provided error log for further tweaks.")
        print("NOTE: Errors possibly encountered due to wrong data type assigned to columns by default. You can use the error log to check which tables are throwing errors and specify the actual data types needed in the provided custom_data_types file")    
        print("Extra NOTE: This may not guarantee all data types would be probably set, so please check out your database for further tweaks")
    print("Constraint/Index Addition Execution time: ",default_timer()-execution_start)
